#!/usr/bin/env python3
"""
trim_bootstrap.py - generate commanddata_cv710_fast.cpp from the full CV710
bootstrap capture.

Why this is safe (same end state, fewer transfers):

1. Every `>02...` token is a host-initiated I2C *status read* and every `<N`
   that follows it is that read's response. Reads are passive: dropping them
   cannot change register state. The subsequent write commands are verbatim
   capture bytes, so their values do not depend on what the reads returned.

2. The driver's poll loops appear as long runs of *identical* blocks of pure
   I2C writes (e.g. writing 0x00 to a row of status registers, repeated 64x,
   with reads sprinkled between). Once the reads are gone the repeated blocks
   become adjacent, and a run-length pass collapses each run to a single copy.
   Writing the same value to the same register repeatedly is idempotent, so
   collapsing does not change the final register state. Blocks whose last
   iteration differs are outside the collapsed run and are preserved verbatim.

3. FPGA/FX3 vendor commands (0x03/0x05/0x06/0x07/0x08/0x09/0x0B/0x0E ...) and
   their request/response pairs are kept intact and in order.

Net effect: identical write sequence, identical final state, 8x fewer USB
transfers (all I2C polling round-trips removed).
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src/liblgx/liblgx-common/src/bootstrap/commanddata_cv710.cpp"
DST = REPO / "src/liblgx/liblgx-common/src/bootstrap/commanddata_cv710_fast.cpp"


def tokenize(src_text: str):
    body = re.search(r"cv710_setup_commands\{(.*?)\};", src_text, re.S)
    if not body:
        raise SystemExit("could not find cv710_setup_commands in source")
    return re.findall(r"[<>][0-9A-Fa-f]+\b", body.group(1))


def drop_i2c_reads(toks):
    """Remove 0x02 I2C read requests and the <N response that follows each."""
    out = []
    i = 0
    while i < len(toks):
        tok = toks[i]
        if tok[0] == ">" and len(tok) > 2 and tok[1:3].lower() == "02":
            i += 1
            if i < len(toks) and toks[i][0] == "<":
                i += 1
            continue
        out.append(tok)
        i += 1
    return out


def is_i2c_write(tok):
    return tok[0] == ">" and len(tok) > 2 and tok[1:3].lower() == "01"


def rle_i2c(toks, max_period=48):
    """Collapse runs of repeated identical blocks of pure I2C writes."""
    out = []
    i = 0
    removed = 0
    while i < len(toks):
        found = False
        for n in range(1, max_period + 1):
            if not all(is_i2c_write(t) for t in toks[i:i + n]):
                continue
            if i + 2 * n > len(toks):
                break
            if toks[i:i + n] == toks[i + n:i + 2 * n]:
                k = 2
                while i + (k + 1) * n <= len(toks) and toks[i + k * n:i + (k + 1) * n] == toks[i:i + n]:
                    k += 1
                out.extend(toks[i:i + n])
                removed += (k - 1) * n
                i += k * n
                found = True
                break
        if not found:
            out.append(toks[i])
            i += 1
    return out, removed


def main():
    toks = tokenize(SRC.read_text())
    d = drop_i2c_reads(toks)
    c, removed = rle_i2c(d)

    print(f"full capture tokens:      {len(toks)}")
    print(f"after dropping I2C reads: {len(d)}")
    print(f"after poll-loop collapse: {len(c)} (removed {removed} duplicate writes)")
    print(f"compression:              {len(toks) / len(c):.1f}x")

    from collections import Counter
    cls = Counter()
    for t in c:
        if t[0] == "<":
            cls["IN"] += 1
        else:
            cls["OUT:" + t[1:3]] += 1
    print("composition:", dict(cls))

    generated = (
        "// Generated by tools/trim_bootstrap.py - DO NOT EDIT BY HAND.\n"
        "//\n"
        "// Fast-start bootstrap: the full cv710_setup_commands capture with all\n"
        "// I2C status-read round-trips removed and the driver's poll-loop\n"
        "// (identical repeated I2C writes) collapsed to a single copy. The write\n"
        "// sequence and final register state are identical to the full capture;\n"
        "// only the passive reads and idempotent repeats are gone.\n"
        "//\n"
        "// Re-generate with:  python3 tools/trim_bootstrap.py\n"
        "\n"
        "#include <string>\n"
        "\n"
        "std::string cv710_setup_commands_fast{\n"
        "    \"" + " ".join(c) + "\"};\n"
    )
    DST.write_text(generated)
    print(f"wrote {DST}")


if __name__ == "__main__":
    main()